version: "3.8"

services:
  db:
    image: postgres:9.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: FitnessTracking
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    image: fitnesstracking   
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=FitnessTracking;Username=postgres;Password=12345
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
